version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    volumes:
      - ./app:/app
    networks:
      - mynetwork

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
